---
- name: Configure Web Server with Nginx
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple HTML file
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello, World!</h1>
          <p>Welcome to my static page served by Nginx on AWS EC2.</p>
          </body>
          </html>

    - name: Generate a self-signed SSL Certificate
      shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=NY/L=New York/O=Example Company/OU=Org/CN=alwayswork.space"
      args:
        creates: /etc/ssl/certs/nginx-selfsigned.crt

    - name: Configure Nginx for HTTPS and redirect HTTP to HTTPS
      blockinfile:
        path: /etc/nginx/sites-available/default
        block: |
          server {
              listen 80;
              server_name alwayswork.space;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name alwayswork.space;

              ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
              ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

              location / {
                  root   /var/www/html;
                  index  index.html index.htm;
              }
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
