---
- name: Configure Web Server with Nginx
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple HTML file
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello, World!</h1>
          <p>Welcome to my static page served by Nginx.</p>
          </body>
          </html>

    - name: Generate a self-signed SSL Certificate
      shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=ID/L=Meridian/O=OSO7/OU=AI/CN=localhost"
      args:
        creates: /etc/ssl/certs/nginx-selfsigned.crt

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx server block file
      copy:
        dest: "/etc/nginx/sites-available/my_site"
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              listen 443 ssl default_server;
              listen [::]:443 ssl default_server;
              ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
              ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

              root /var/www/html;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Enable the Nginx server block
      shell: ln -s /etc/nginx/sites-available/my_site /etc/nginx/sites-enabled/my_site
      args:
        creates: /etc/nginx/sites-enabled/my_site

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded
